---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-testing
  namespace: application
  labels:
    app: ansible-testing
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ansible-testing
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: ansible-testing
        app: ansible-testing
        app.kubernetes.io/instance: ansible-testing
        art: opf
        domain: ordermanagement
        market: shared
        scope: public
        team: oak-mountain
    spec:
      serviceAccountName: ansible-testing
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: eks.amazonaws.com/capacityType
                    operator: In
                    values:
                      - SPOT
              weight: 1
      containers:
        - name: ansible-testing
          image: 625624957199.dkr.ecr.us-east-1.amazonaws.com/ansible-testing:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ansible-testing
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          volumeMounts:
            - mountPath: /secrets
              name: kv-secrets
              readOnly: true
          resources:
            limits:
              cpu: 800m
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - 'curl -m 1 -f localhost:8081/admin/health'
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - 'curl -m 1 -f localhost:8081/admin/health'
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 2
          startupProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - 'curl -m 1 -f localhost:8081/admin/health'
            failureThreshold: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        fsGroup: 65534
      terminationGracePeriodSeconds: 30
      volumes:
        - name: kv-secrets
          projected:
            defaultMode: 420
            sources:
              - secret:
                  name: ansible-testing
                  optional: true