---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ansible-testing
  namespace: application

spec:

  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore

  target:
    name: ansible-testing

  data:
