---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:

  - path: ./patches/sa.yaml
    target:
      group: ''
      version: v1
      kind: ServiceAccount
      namespace: application
      name: ansible-testing

  - path: ./patches/cm.yaml
    target:
      group: ''
      version: v1
      kind: ConfigMap
      namespace: application
      name: ansible-testing